### ISSUE TITLE
Push new images to docker hub

### ISSUE THREAD

**Issue by fwilhe** [rochdev/docker-alpine-asciidoctor#4]
Hello,
first of all: Thanks for providing those images. I think they are very good suited for converting AsciiDoc files via CI.

I noticed that the images are a year old. It would be nice if they were updated with the latest version of Asciidoctor, since it has made some progress in that time.

**Comment by rochdev** [comment]
@fwilhe I'll try to get new images out by this weekend

**Comment by rochdev** [comment]
New images are live! 🎉
